services:
  # Laravel application service (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "9000:9000"  # Exposing PHP-FPM port
    environment:
      - COMPOSE_PROJECT_NAME=laravel

  # Nginx service to serve the application
  web:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Nginx config file
    networks:
      - app-network
    ports:
      - "8080:80"  # Exposing Nginx port to localhost
    depends_on:
      - app

  # MySQL database service
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_app
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  # Vite service for frontend assets (running in development mode)
  vite:
    build:
      context: .
      dockerfile: Dockerfile  # We use the same Dockerfile to install dependencies
    container_name: vite
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    environment:
      - COMPOSE_PROJECT_NAME=laravel
    command: npm run dev  # Running the Vite development server
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:  # Persistent storage for MySQL data
