name: Build and deploy PHP app to Azure Web App - hiveapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress --no-dev --optimize-autoloader

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Node dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Laravel Post-Install Commands (Local)
        run: |
          php artisan config:clear
          php artisan storage:link
        continue-on-error: true  # Proceed even if storage link fails (handled on App Service)

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: |
            .
            !node_modules  # Exclude node_modules if built locally
            !vendor        # Exclude vendor if built locally

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A68648C7A7B04C23968CDA9474A0BA27 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3932F4996B3E4FEAAF7A2B9A4FAAAE11 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D5FFCF0E3CD5489D84756D379097ADA7 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'hiveapp'
          slot-name: 'Production'
          package: .

      - name: Laravel Post-Install Commands (App Service)
        run: |
          # Ensure storage and cache are writable
          chmod -R 775 storage bootstrap/cache
          # Re-run critical commands
          php artisan migrate --force
          php artisan migrate --force --database=mongodb
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
        working-directory: .
        continue-on-error: true  # Log errors but proceed

      - name: Restart App Service
        run: az webapp restart --name hiveapp --resource-group <your-resource-group>
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
